### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by vkumra-broad** [jupyterlab/jupyterlab-commenting#16]
Hi folks

I am trying to install using the command in the readme and am getting a 404 error

This is what I am using 

`jupyter labextension install jupyterlab-commenting`

and the output is 

```
> /usr/bin/npm pack jupyterlab-commenting
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code E404
npm ERR! 404 Not Found: jupyterlab-commenting@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jupyter-user/.npm/_logs/2019-04-12T15_26_53_372Z-debug.log

Errored, use --debug for full output:
ValueError: "jupyterlab-commenting" is not a valid npm package
```

Any idea what the issue is here? 
npm version = 5.8.0
node version = v10.15.1

Thanks

**Comment by saulshanabrook** [comment]
Hey @vkumra-broad we don't have a release yet of this package!

We [should clarify the readme](https://github.com/jupyterlab/jupyterlab-commenting/pull/17) to be clear about that.

We do have a demo of this up and running with a development version of JupyterLab: https://github.com/jupytercalpoly/rich-context-demo

**Comment by vkumra-broad** [comment]
Thanks for the clarification!
