### ISSUE TITLE
First release publish on npm

### ISSUE THREAD

**Issue by hoo761** [jupyterlab/jupyterlab-commenting#31]
@ellisonbg, Jupyterlab commenting is ready to be released on npm. 

If there is anything that is needed to be added before it is published to npm, let me know.

My username for npm is `hoo761` so you can add me to the package.

**Comment by gogasca** [comment]
@hoo761 does this mean I can install it in my Jupyter instance?

**Comment by hoo761** [comment]
@gogasca Not from npm yet. It needs to be published to the official Jupyterlab npm account. Once that is done, the normal installation through npm will work. For now, only the developer build of commenting works.

**Comment by gogasca** [comment]
Thanks @hoo761 will keep an eye on the official npm, is there an ETA on that?
Thanks again

**Comment by hoo761** [comment]
@gogasca The extension is now published and the install command in the readme will work.
