### ISSUE TITLE
Summer design notes

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab-commenting#4]
This is a summary of design notes from the student intern team at Cal Poly that worked on the UI/UX of commenting and annotation. These are the notes in the end-of-summer state:

## Assumptions and design constraints

* All users are identified
* No one is evil (focused on small team collaboration, not open-moderated discussion)
* Documents and other content change over time and a full time history of the document will be available (backed by VCS or real-time data model)

## Design concepts

* Time/history
  - The state of a document moves forward in time and only comments pertaining to targets that exist at that moment in time will show.
  - At a given moment in time, comments can be open or resolved. Resolved comments only show if that option is toggled on.
  - If the document is viewed at a previous moment in time, only the comments at that time will show.
  - If a target is deleted, the document moves forward in time and comments attached to that deleted target are only visible in the past.
  - Deleting a comment does not move the document forward in time.
  - When looking in the past, comments are shown in the state (resolved/open) that they were in at that moment.
  - In the past, no changes can be made. In other words, changes alway move time forward.
* Delete/resolve
  - Delete removes a comment from all of time.
  - Resolve causes a comment to be hidden unless option to view resolved is selected.
  - Resolved comments only show if the target exists at that moment in time.
  - Anyone can resolve and reopen a comment thread.
  - Deleting a comment can be undone? (UX Question)
* Edit
  - Edited comments show that they were edited.
  - Edited comments have a time change.
* Targets/comments/thread
  - Each comment thread is associated with a target - the thing being commented on.
  - Display a comment target marker icon that can be clicked to focus the comment thread and possibly display other indicators of the target (such as text highlight).
  - Show the target markers for both open and resolved comments, but color differently    
  - Offer a UI in the comment panel for hiding/showing resolved comments. Current thought is to use the R sidebar in JLab.
  - If comment threads have “nearby” targets, show a single comment target marker (for example one per line) for the group. We could put a number in the target marker to indicate how many comment threads there are. Somehow show the group of them in the comment panel. Initially, don’t expand any of the comments in the group, but then allow the user to click on one of them to expand it.
  - When a comment thread is unfocused, only show the first comment, when it is selected/focused, show all replies.
  - Comments can be canceled before posting

## Design atoms/molecules

* Comment target marker
  - Marker at R edge of document.
  - Highlight (when focused) target.
* Comment panel
  - Date/time of document/comments
  - Sections?
    - Resolved
    - Open
  - Comment thread
    - Resolve button (if open)
    - Twisty button
    - Reopen button (if resolved)
    - Close button (to cancel action)    
    - Individual comment
      - Name of the user, maybe photo
      - Date/time
      - Body
      - Actions UI (if your own)
    - Reply field
    - Cancel button

**Comment by tgeorgeux** [comment]
I wanted to jump on this after some initial explorations hone in a little bit on the structure we want. I'll input thoughts on what should be added/altered below:

## Assumptions and design constraints

* Comment threads are stand-alone entities, they will be viewed/resolved in a stand-alone manner, and won't be linked (like github issues can be linked).

## Design concepts

* Time/history
  - In the past, no changes can be made. In other words, changes alway move time forward.
    -(Question) Will we have a notion of 'restoring' a target into 'current time' that will allow the targeted comments to update with them?
* Delete/resolve
  - Delete removes a comment from all of time.
    -(Question) Should we delete, or archive old comments? Do we want to allow a removal of the record of previous conversations that's fully un-recoverable?
  - Deleting a comment can be undone? (UX Question)
    - (Question) Related to above, if deleted comments are archived instead, they can be retrieved. If we're building this based of the use of private data stores, wouldn't a 'cover your tracks' functionality be a potential for abuse, even in a trusted environment?
* Edit
  - Edited comments show that they were edited.
    - (Question) Do they show edit history?
  - Edited comments have a time change.
* Targets/comments/thread
  - Show the target markers for both open and resolved comments _(Depending on selection made in comment viewing pane)_, but color differently.
  - When a comment thread is unfocused, only show the first comment, when it is selected/focused, show all replies. _In addition, when expanded, show the only the expanded comment in a single thread_ (based on the new constraint above)

## Design atoms/molecules

* Comment target marker
  - Marker at R edge of document.
    - (Decision point) How to show target markers in the file browser/Data explorer?
  - Highlight (when focused) target.
* Comment panel
  - Sections?
    - Resolved
    - Open
  - Comment thread
    - _Thread Title_
    - Twisty button _Propose changing this to "expand/close button", for single thread view instead of expanding thread view_
    - Close button (to cancel action) _Covered by revised twisty, can remove_
    - Individual comment _/reply_
      - _No title for replies_

See additional discussion and sketches in #5 .

**Comment by saulshanabrook** [comment]
Closing this since we have an initial design implemented. We can open follow up issues for specific changes we would like to implement.
