### ISSUE TITLE
User facing documentation

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-commenting#41]
We should add to the existing GIF in the homepage to outlines how to use this project from a user point of view.

**Comment by kgryte** [comment]
@saulshanabrook Is that not already present both in the README and in the [usage guide](https://github.com/jupyterlab/jupyterlab-commenting/blob/master/USAGE.md)?

**Comment by saulshanabrook** [comment]
Ooh usage guide yeah didn't even see that.... It's really nice! Do you think we should move it to the readme for greater visibility or did you find it ok?

**Comment by kgryte** [comment]
IMO, I think it is fine as a separate doc. Main README provides an overview GIF and links to the USAGE document.
