### ISSUE TITLE
Initial Explorations on Layout.

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab-commenting#5]
I wanted to open this issue to keep everybody updated with my design explorations related to the comments. I have done some initial sketches to work out the basic layout, as well as set the direction for the initial prototype. For a more detailed view of the sketches please see the link: https://www.figma.com/file/gz2J72S4S6BEqwBYh0sh91NT/Commenting-and-Annotations-for-Data-Sets.?node-id=8%3A5 Please feel free to make in-situ comments on the sketches/prototypes themselves and keep higher level discussions in issues so they are easier to reference later. 

####  1 & 2 Exploring design layout
![frame](https://user-images.githubusercontent.com/22109376/50859650-d1351200-1348-11e9-862a-22db55e0f619.png)
Exploring the use of toggles/ multi- selectors to filter comment view.

#### Card Vs List layout
![frame 2](https://user-images.githubusercontent.com/22109376/50859716-f590ee80-1348-11e9-83e1-5076041153a1.png)
Working out how much real estate to give to document-specific data, this would be the state of the right sidebar when viewing comments on unopened data sets in the file/data explorers. I like the idea of having a persistent nav bar in the sidebar instead of a larger field to show more about the data set. As well as a method to toggle view of comments that target the entire data-set (meta comments) vs targets inside the data set (data comments). Cards/list items in these views could be expanded or 'opened' (which denotes a single thread view). 

#### Opening vs Expanding comments
![frame 3](https://user-images.githubusercontent.com/22109376/50859945-89fb5100-1349-11e9-8fff-53c725eed931.png)
![frame 4](https://user-images.githubusercontent.com/22109376/50860107-eeb6ab80-1349-11e9-83fd-9e0269ec6161.png)

For MVP I don't think it's right to build a robust comment-linking system. I think there a discussion to be had about comments vs annotations (comments being inherently transient discussions, and annotations being being semi-permanent additions to the data set), but in the mean time I think it makes sense to design for comment threads to be self-contained and resolved, without reference to other comment threads. 

A couple questions these Sketches bring up to explore:
* How will the comments activity be launched when user is browsing?
  - From Data Explorer?
  - From File Browser?
  - It's always in the right-pane?
* Is there a notion of 'linked-sidebars'? 
  - ie: do we open/close tabs in the right sidebar based on the user's focus?
  - An example of this would be when the data-explorer is open, the meta-data, comments, and links tabs all appear in the right sidebar, and disappear when the data explorer is closed.
* Should we give identifiers for comment threads (titles?)
* States: do we have 'contexual' view of thread?
  - ie: if a dataset is selected but not opened do we show comments tied to fields/rows/columns in the comment pane?

I'm going to continue to iterate on these in Figma now that I've nailed down a few specifics about how to view the comments/threads. Please sound of here for high level critique/input and feel free to add comments in Figma to clarify/suggest on specific interactions.

**Comment by tgeorgeux** [comment]
Update on current screens. 
![no target](https://user-images.githubusercontent.com/22109376/51010134-d12f4080-1507-11e9-8f7e-03e9090f52cf.png)


![loremdata selected](https://user-images.githubusercontent.com/22109376/51010137-d42a3100-1507-11e9-8dfa-13ae3dc792f0.png)


![loremdata selected expand button](https://user-images.githubusercontent.com/22109376/51010141-d7bdb800-1507-11e9-919f-7d1b1eacc967.png)


![loremdata open comment selected](https://user-images.githubusercontent.com/22109376/51010142-d9877b80-1507-11e9-9baf-52adc71112fb.png)

**Comment by karamba228** [comment]
@tgeorgeux We got some updates on the UI
![comment box](https://user-images.githubusercontent.com/25186689/51755876-4745b280-2085-11e9-9a84-2c4fc888640e.png)
![expanded comment](https://user-images.githubusercontent.com/25186689/51755877-4745b280-2085-11e9-841e-0f2af12f8778.png)
![header sort](https://user-images.githubusercontent.com/25186689/51755878-4745b280-2085-11e9-8654-6e864d166229.png)
![reply active](https://user-images.githubusercontent.com/25186689/51755880-4745b280-2085-11e9-9666-a2795bf34f97.png)
